import { NextRequest, NextResponse } from "next/server";
import { createServiceRoleClient } from "@/lib/supabase/service";

// GET /api/admin/lineups/[id]/pdf — generate a printable HTML for a lineup
export async function GET(
  _req: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  const { id } = await params;
  const supabase: any = createServiceRoleClient();

  const { data: lineup, error } = await supabase.from("show_lineups")
    .select(`
      *,
      event:events(id, name, year, start_date, end_date),
      models:show_lineup_models(
        id,
        model_id,
        walk_order,
        outfit_notes,
        status,
        model:models(id, username, first_name, last_name, profile_photo_url, height, bust, hips, dress_size, shoe_size, instagram_url)
      )
    `)
    .eq("id", id)
    .single();

  if (error || !lineup) {
    return NextResponse.json({ error: "Lineup not found" }, { status: 404 });
  }

  const models = (lineup.models || []).sort(
    (a: any, b: any) => a.walk_order - b.walk_order
  );

  const event = lineup.event as any;
  const designerName = lineup.designer_name || "Designer";
  const showDate = lineup.show_date
    ? new Date(lineup.show_date + "T00:00:00").toLocaleDateString("en-US", {
        weekday: "long",
        month: "long",
        day: "numeric",
        year: "numeric",
      })
    : "TBD";

  const html = `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>${designerName} - Show Lineup</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { font-family: 'Helvetica Neue', Arial, sans-serif; color: #111; padding: 40px; max-width: 800px; margin: 0 auto; }
    .header { text-align: center; margin-bottom: 32px; border-bottom: 2px solid #111; padding-bottom: 20px; }
    .header h1 { font-size: 28px; font-weight: 700; letter-spacing: 2px; text-transform: uppercase; }
    .header h2 { font-size: 18px; font-weight: 400; color: #555; margin-top: 4px; }
    .meta { display: flex; justify-content: space-between; margin-top: 12px; font-size: 13px; color: #666; }
    .models-table { width: 100%; border-collapse: collapse; margin-top: 24px; }
    .models-table th { text-align: left; padding: 8px 12px; font-size: 11px; text-transform: uppercase; letter-spacing: 1px; color: #888; border-bottom: 1px solid #ddd; }
    .models-table td { padding: 10px 12px; border-bottom: 1px solid #eee; font-size: 13px; vertical-align: middle; }
    .models-table tr:hover { background: #f9f9f9; }
    .walk-num { font-weight: 700; font-size: 16px; color: #333; text-align: center; width: 40px; }
    .model-name { font-weight: 600; }
    .model-username { color: #888; font-size: 12px; }
    .notes { font-style: italic; color: #666; font-size: 12px; }
    .footer { margin-top: 32px; text-align: center; font-size: 11px; color: #aaa; border-top: 1px solid #ddd; padding-top: 16px; }
    .total { margin-top: 16px; text-align: right; font-size: 13px; color: #666; }
    @media print { body { padding: 20px; } }
  </style>
</head>
<body>
  <div class="header">
    <h1>${designerName}</h1>
    <h2>${lineup.name}</h2>
    <div class="meta">
      <span>${event?.name || "Event"} ${event?.year || ""}</span>
      <span>${showDate}${lineup.show_time ? " at " + lineup.show_time : ""}</span>
      <span>Status: ${lineup.status.toUpperCase()}</span>
    </div>
  </div>

  <table class="models-table">
    <thead>
      <tr>
        <th style="width:40px">#</th>
        <th>Model</th>
        <th>Height</th>
        <th>Measurements</th>
        <th>Shoe</th>
        <th>Instagram</th>
        <th>Notes</th>
      </tr>
    </thead>
    <tbody>
      ${models
        .map((lm: any, i: number) => {
          const m = lm.model;
          const measurements = [m?.bust, m?.hips].filter(Boolean).join(" / ") || "\u2014";
          const ig = m?.instagram_url
            ? m.instagram_url.replace(/https?:\/\/(www\.)?instagram\.com\//, "@").replace(/\/$/, "")
            : "\u2014";
          return `
      <tr>
        <td class="walk-num">${i + 1}</td>
        <td>
          <div class="model-name">${m?.first_name || ""} ${m?.last_name || ""}</div>
          <div class="model-username">@${m?.username || "\u2014"}</div>
        </td>
        <td>${m?.height || "\u2014"}</td>
        <td>${measurements}</td>
        <td>${m?.shoe_size || "\u2014"}</td>
        <td>${ig}</td>
        <td class="notes">${lm.outfit_notes || ""}</td>
      </tr>`;
        })
        .join("")}
    </tbody>
  </table>

  <div class="total">${models.length} models in lineup</div>

  <div class="footer">
    Generated by EXA Platform \u00b7 ${new Date().toLocaleDateString("en-US", { month: "long", day: "numeric", year: "numeric" })}
  </div>
</body>
</html>`;

  return new NextResponse(html, {
    headers: {
      "Content-Type": "text/html; charset=utf-8",
      "Content-Disposition": `inline; filename="lineup-${designerName.replace(/\s+/g, "-").toLowerCase()}.html"`,
    },
  });
}
