export type Video = {
  id: string;
  youtubeId: string;
  title: string;
  category: string;
  featured?: boolean;
};

export const TV_VIDEOS: Video[] = [
  // Miami Swim Week - Runway Shows
  { id: "1", youtubeId: "QFDBeGQILzY", title: "Exa Models Full Day 1 Show | Miami Swim Week 2025 [4K]", category: "MSW", featured: true },
  { id: "2", youtubeId: "Y1vyiIpJhHA", title: "Exa Models Full Day 2 Show | Miami Swim Week 2025 [4K]", category: "MSW", featured: true },
  { id: "3", youtubeId: "Cc0N7a-eCZw", title: "Exa Swim 4K | Miami Swim Week 2025", category: "MSW" },
  { id: "4", youtubeId: "LyMckCEBd4A", title: "EXA SWIM / Miami Swim Week / Exa Shows", category: "MSW" },
  { id: "5", youtubeId: "TnoZi5vL7Vk", title: "Exa Swimwear 4K | Fashion Runway Full Show", category: "MSW" },
  { id: "6", youtubeId: "6m3C7xIPB4A", title: "Super Color Swim in 4K | Miami Swim Week 2025 | EXA Swim Shows", category: "MSW" },
  { id: "7", youtubeId: "CyXsa4-yi7U", title: "Color Super Swim Full Show 4K | Miami Swim Week 2025", category: "MSW" },
  { id: "8", youtubeId: "wFvgmtTRbGo", title: "COLOR SUPER Swim Miami Swim Week 2025 [4K]", category: "MSW" },
  { id: "9", youtubeId: "lYzSnPZ-peE", title: "COLOR SUPER / Miami Swim Week / Exa Shows", category: "MSW" },
  { id: "10", youtubeId: "iY8oHBP0czU", title: "ColorSuper Bikinis Miami Swim Week 2025 | Exa Shows", category: "MSW" },
  { id: "11", youtubeId: "00aJzz0qEcA", title: "Veve Swim Full Show 4K | Miami Swim Week 2025", category: "MSW" },
  { id: "12", youtubeId: "6vVDtHJFXk4", title: "Veve Swimwear 4K | Fashion Runway Full Show", category: "MSW" },
  { id: "13", youtubeId: "Qxi9oHMvrH8", title: "VEVE SWIM / Miami Swim Week / Exa Shows", category: "MSW" },
  { id: "14", youtubeId: "A5oiq5XhylI", title: "Mariella Swimwear | Miami Swim Week 2025", category: "MSW" },
  { id: "15", youtubeId: "aSo3-aF0ERQ", title: "MARIELLA SWIM / Miami Swim Week / Exa Shows", category: "MSW" },
  { id: "16", youtubeId: "JZNTZsJDKuI", title: "Mariella Swim Runway Show During Miami Swim Week 2025 | EXA Swim Shows", category: "MSW" },
  { id: "18", youtubeId: "TEqGkid7M7o", title: "Crocodile Collections by Marielle Swim | Swim Shows | Exa Swim Shows 2025", category: "MSW" },
  { id: "19", youtubeId: "mU0A202Dik8", title: "Capristan Swim Full Show | Miami Swim Week 2025", category: "MSW" },
  { id: "20", youtubeId: "PTaE4eTGAWg", title: "Capristan Turns Heads at Miami Swim Week 2025", category: "MSW" },
  { id: "21", youtubeId: "X9kA6BWWY2c", title: "CAPRISTAN / Miami Swim Week 2025 / Exa Shows", category: "MSW" },
  { id: "22", youtubeId: "Kowpi6S7UO0", title: "Bronzed Babe Swim | Miami Swim Week 2025", category: "MSW" },
  { id: "23", youtubeId: "VykF9PVNXHk", title: "BRONZED BABE SWIM / Miami Swim Week / Exa Shows", category: "MSW" },
  { id: "25", youtubeId: "onz6kpDmO3g", title: "Suzu Swimwear Miami Swim Week 2025 Full Show in 4K | Swim Shows", category: "MSW" },
  { id: "26", youtubeId: "72wRZWY8SRE", title: "SUZU SWIMWEAR / Miami Swim Week / Exa Shows", category: "MSW" },
  { id: "27", youtubeId: "MwD0IK_NEqs", title: "Suzu Swim at Exa Shows | Miami Swim Week 2025", category: "MSW" },
  { id: "28", youtubeId: "m12eYGVc4Yg", title: "Sherbert Lemons Full Show in 4K / Miami Swim Week / Exa Shows", category: "MSW" },
  { id: "29", youtubeId: "LRzzpEl7kiU", title: "Sherbet Lemons Swimwear Show | Miami Swim Week 2025", category: "MSW" },
  { id: "30", youtubeId: "lh-di3iX1uI", title: "Pia Bolte Full Show in 4K / Miami Swim Week / Exa Shows", category: "MSW" },
  { id: "31", youtubeId: "yU6lVxgVAfU", title: "Pia Bolte Swim 4K | Miami Swim Week 2025", category: "MSW" },
  { id: "32", youtubeId: "vdt1lbuJC24", title: "Sewhi Kinis Exa Models Miami Swim Week 2025 [4K]", category: "MSW" },
  { id: "33", youtubeId: "bYzzNSEEKuM", title: "SEWHI KINIS / Miami Swim Week / Exa Shows", category: "MSW" },
  { id: "34", youtubeId: "9RFm_jgvjK4", title: "Goalden Swimwear | Swim Shows | Exa Miami Swim Week 2025", category: "MSW" },
  { id: "35", youtubeId: "g2Il6jXLwRw", title: "GOALDEN SWIMWEAR / Miami Swim Week / Exa Shows", category: "MSW" },
  { id: "36", youtubeId: "x4AB3dFsMKs", title: "Bikini Flavors Swimwear | Miami Swim Week 2025", category: "MSW" },
  { id: "37", youtubeId: "ns1wW6t2ZQs", title: "SUGARBUSH / Miami Swim Week / Exa Shows", category: "MSW" },
  { id: "38", youtubeId: "ll1TPIm_XlQ", title: "IVY Swimwear | Fashion Runway Full Show", category: "MSW" },
  { id: "39", youtubeId: "XEFJeKq4o2I", title: "BAY Swimwear | Fashion Runway Full Show", category: "MSW" },
  { id: "40", youtubeId: "p2neBy7V-mY", title: "Berry Beachy Swimwear | Fashion Runway Full Show", category: "MSW" },
  { id: "41", youtubeId: "GyuzgNBmcgY", title: "Meduza Swimwear 4K | Fashion Runway Full Show", category: "MSW" },
  { id: "42", youtubeId: "9s8Z7NHfF8Y", title: "LB Fashion's Insane Show at EXA Shows, Miami Swim Week", category: "MSW" },
  { id: "43", youtubeId: "0OhZp4FSiMU", title: "ORIGIN OF OCEANS / Swim Week Miami / Exa Shows", category: "MSW" },
  { id: "44", youtubeId: "urjn8b1O5Wk", title: "GARI FASHION / Miami Swim Week / Exa Shows", category: "MSW" },
  { id: "45", youtubeId: "ttK5mMYTkQA", title: "Miami Swim Week At The Moore Heats Up!", category: "MSW" },
  { id: "46", youtubeId: "xQ-sDj8CK-A", title: "Miami Swim Week 2025 At The Moore", category: "MSW" },

  // Miami Art Week / Art Basel
  { id: "47", youtubeId: "Iu68o0MCuvw", title: "Color Super Takes Over Miami Art Basel 2024 Exa Shows!", category: "MAW" },
  { id: "48", youtubeId: "QP7h6dc9YTc", title: "The MOST INSANE Art Basel Show in 2024 - Josie Bikini's by Exa Shows!", category: "MAW" },
  { id: "49", youtubeId: "G9eoxsUSa5E", title: "Capristan Swim Runway | Miami Art Basel Fashion Show", category: "MAW" },
  { id: "50", youtubeId: "v5MgC0YjLvw", title: "Monaco Swim Unveiled: Bold & Exclusive at Art Basel Miami Exa Shows in 4K", category: "MAW" },
  { id: "51", youtubeId: "9yInHSSOT20", title: "Bikini Flavors Steals the Runway at Miami Art Basel 2024", category: "MAW" },

  // NYFW
  { id: "52", youtubeId: "IRWcdfdTc4k", title: "Model Victoria Vesce Interviewed at Exa Shows NYFW", category: "NYFW" },
  { id: "53", youtubeId: "pQvQFbLTzZM", title: "Bikini Model Lorimer Mauricio at EXA Swim Shows in NYC", category: "NYFW" },

  // Behind the Scenes
  { id: "54", youtubeId: "WGbjoyq09H0", title: "Exa Models Casting Miami Swim Week 2025 [4K]", category: "Behind the Scenes", featured: true },
  { id: "55", youtubeId: "tUzkvoJsiRU", title: "Who Gets Picked? ONE HOUR of Exclusive Bikini Model Casting | Miami Swim Week 2025", category: "Behind the Scenes" },
  { id: "56", youtubeId: "9JDS57YIyb0", title: "Models Sydney Thomas & Anna Gagliano Backstage at EXA Swim Week in Miami", category: "Behind the Scenes" },
  { id: "57", youtubeId: "K0egMLGe0so", title: "Karen Rodriguez in Slow Motion | Miami Swim Week 2025", category: "Behind the Scenes" },
  { id: "58", youtubeId: "zdeZhSIncXo", title: "Model Sarah Interviews Mia Torrence and Nat Cruzzz at EXA Shows Miami Swim Week", category: "Behind the Scenes" },
  { id: "59", youtubeId: "faAncNuyjCY", title: "Diana Lapo and Sister After Exa Shows Miami Swim Week", category: "Behind the Scenes" },

  // Miami Swim Week - additional uploads
  { id: "60", youtubeId: "LSLmAJ2_pXo", title: "Miami Swim Week | Top Swimwear Designs Bikinis | EXA Models | Best Highlights", category: "MSW" },
  { id: "61", youtubeId: "ftoME_KaXG0", title: "Alice.rosenblum Exa Models Miami 2025 [4K]", category: "MSW" },
  { id: "62", youtubeId: "5eFYKY2iIBE", title: "Mariella Swim GOT THE WHOLE RUNWAY SHOOK at EXA Models Swim Show!", category: "MSW" },
  { id: "63", youtubeId: "v7-2LzGFoz0", title: "Exa Models showcases Super Bikini Swimwears | Best Highlights Miami Swim Week 2025", category: "MSW" },
  { id: "64", youtubeId: "dTKqvfmtiWU", title: "Highlights Miami Swim Week 2025 | EXA Models Slayed the Runway with the Best Bikinis", category: "MSW" },
  { id: "65", youtubeId: "nPsExYz8DFg", title: "Exa Models Salvatore Settegrana Miami Swim Week Fashion Show Bikini Looks - Part 2", category: "MSW" },
  { id: "66", youtubeId: "lEk56eGmRgM", title: "BEST EXA MODELS | Best Bikinis Design | Highlights Miami Fusion", category: "MSW" },
  { id: "67", youtubeId: "xE7-VStBWsA", title: "Part 2 Mariella Swim GOT THE WHOLE RUNWAY SHOOK at EXA Models Swim Show!", category: "MSW" },
  { id: "68", youtubeId: "51iHodgTyUA", title: "Exa Models Miami Swim Week Fashion Show Bikini Best Summer Looks - Part 4", category: "MSW" },
  { id: "69", youtubeId: "BiwbnFECSmM", title: "Exa Models Full Show Day 3 | Miami Swim Week 2025 [4K]", category: "MSW" },
  { id: "70", youtubeId: "BV9w9hCH6qw", title: "Alice.rosenblum Exa Models Runway 2025 [4K]", category: "MSW" },
  { id: "71", youtubeId: "_bXh_aXNWcA", title: "Luxury Bikinis Highlights Miami 2025 | THE BEST EXA Models Design", category: "MSW" },
  { id: "72", youtubeId: "P6ILfFL7zCE", title: "EXA Models | Bikini Swimwear from SAHAI SWIM | Highlights Miami Swim Week 2025", category: "MSW" },
  { id: "73", youtubeId: "-K1OMoMF0FE", title: "Exa Models Gia and Viviana | Miami Swim Week 2025 [4K]", category: "MSW" },
  { id: "74", youtubeId: "mRR4pQ4991U", title: "Luxury High End Bikinis Design Highlights Miami 2025 | EXA Models are the BEST", category: "MSW" },
  { id: "75", youtubeId: "E9XChw8EzQw", title: "Mariana Morais IN SLOMO | Exa Models | Miami Swim Week 2025", category: "MSW" },
  { id: "76", youtubeId: "ekL0EXLQVLY", title: "Exa Models Kickoff at the Moore Bikini Fashion Show during Miami Swim Week 2025", category: "MSW" },
  { id: "77", youtubeId: "DRaADYNGSK4", title: "Bikinis Swimwear & Top EXA Models | Miami Swim Week Best Highlights", category: "MSW" },
  { id: "78", youtubeId: "MxGzjVuWFLo", title: "[SLOMO] EXA Models | Designer Goalden Swimwear | Miami Swim Week", category: "MSW" },
  { id: "79", youtubeId: "9SzxpUCyP-g", title: "Exa Models Final Show Miami Swim Week Bikini Fashion Summer Best Looks Part 3", category: "MSW" },
  { id: "80", youtubeId: "YRgTSdDM0YA", title: "Top EXA Models | Miami Swim Week | Best Bikinis Swimwear Highlights", category: "MSW" },
  { id: "81", youtubeId: "Ew_9KhxIq1o", title: "Best Latina Bikini Swimwear Exa Models at Miami Swim Week 2025", category: "MSW" },
  { id: "82", youtubeId: "iuzjC1mth-k", title: "Exa Models Brittany and Athena | Miami Swim Week 2025 [4K]", category: "MSW" },
  { id: "83", youtubeId: "JGzKPgotINs", title: "Goalden Swimwear | Exa Models | Swim Shows | Miami Swim Week 2024", category: "MSW" },
  { id: "84", youtubeId: "cFmothCCxzw", title: "Exa Models Miami Swim Week Fashion Show Bikini Best Summer Looks - Part 2", category: "MSW" },
  { id: "85", youtubeId: "7Dv0MGyrHK0", title: "Kayla Manousselis IN SLOMO | Exa Models | Miami Swim Week 2025", category: "MSW" },
  { id: "86", youtubeId: "DKBEF2hjKHo", title: "Coconut Bikini | Exa Models | Swim Shows | Miami Swim Week 2024", category: "MSW" },
  { id: "87", youtubeId: "pEDVt-53Yss", title: "Exa Models @TaylorShay4L | Miami Swim Week 2025 [4K]", category: "MSW" },
  { id: "88", youtubeId: "4y7RCQn9klk", title: "Stunning EXA Models at Miami Swim Week 2025", category: "MSW" },
  { id: "89", youtubeId: "Cs8buUvBWBM", title: "Featured Group | EXA MODELS | Designer OCEAN OF ORIGINS | Miami Swim Week 3", category: "MSW" },
  { id: "90", youtubeId: "nnMUY0EFP3U", title: "Exa Models Danielle and Kaley | Miami Swim Week 2025 [4K]", category: "MSW" },
  { id: "91", youtubeId: "AMUnwWzoMkU", title: "Exa Models Miami Swim Week Fashion Show Bikini Best Summer Looks - Part 3", category: "MSW" },
  { id: "92", youtubeId: "UYRITyeiWDQ", title: "Designer Swimwear & Bikinis | Miami Swim Week | Exa Models showcases Berry Beach, Euforia, Goalden", category: "MSW" },
  { id: "93", youtubeId: "Pjdo-ugipzo", title: "Euphoria Swim | Exa Models | Swim Shows | Miami Swim Week 2024", category: "MSW" },
  { id: "94", youtubeId: "-x5f2oOO45I", title: "Exa Models Final Show Miami Swim Week Bikini Fashion Summer Best Looks Part 1", category: "MSW" },
  { id: "95", youtubeId: "FcDSSt9b4Ck", title: "Exa Models Run the Runway | Best Looks at Miami Swim Week 2025", category: "MSW" },
  { id: "96", youtubeId: "_5UW4ahWQb0", title: "Beatrice Corbett in Jaw-Dropping SLOMO | Exa Models | Miami Swim Week 2025", category: "MSW" },
  { id: "97", youtubeId: "CfbqrRUNT08", title: "Best Exa Models Bikini Walks | Miami Swim Week 2025 Highlights", category: "MSW" },
  { id: "98", youtubeId: "JtbmHGUudF4", title: "[SLOMO] EXA Models | Designer Piura | Miami Swim Week", category: "MSW" },
  { id: "99", youtubeId: "Nf2eRIHshYo", title: "Karen Rodriguez | Exa Models | Slow Motion | Miami Swim Week 2024", category: "MSW" },
  { id: "100", youtubeId: "rOkh3D-ujKQ", title: "Featured Group | EXA MODELS | Designer ORIGIN OF OCEANS | Miami Swim Week 1", category: "MSW" },
  { id: "101", youtubeId: "Nlgqh3HQDr8", title: "Sugar Bush Bikinis Exa Models Miami Swim Week Fashion Show Part 3", category: "MSW" },
  { id: "102", youtubeId: "X2VGFUoit3M", title: "Milus Rose | Exa Models | Swim Shows | Miami Swim Week 2024", category: "MSW" },
  { id: "103", youtubeId: "NpDkNuLyCCs", title: "Featured Group | EXA MODELS | Designer ORIGIN OF OCEANS | Miami Swim Week 2", category: "MSW" },
  { id: "104", youtubeId: "fsK_wvmur38", title: "Exa Models Sugar Bush Bikinis Miami Swim Week Fashion Show Part 1", category: "MSW" },
  { id: "105", youtubeId: "l9yxi5r1bqE", title: "EXA Models Swim Shows | Coconut Bikini Swimsuit Swimwear | Miami Swim Week", category: "MSW" },
  { id: "106", youtubeId: "9gAdohrEW5Q", title: "Exa Models Final Show Miami Swim Week Bikini Fashion Summer Best Looks Part 4", category: "MSW" },
  { id: "107", youtubeId: "ExLbijx1xvY", title: "Exa Models Salvatore Settegrana Miami Swim Week Fashion Show Bikini Looks - Part 1", category: "MSW" },
  { id: "108", youtubeId: "ouTDWwnVAU8", title: "Featured Group | EXA MODELS | Designer ORIGIN OF OCEANS | Miami Swim Week 5", category: "MSW" },
  { id: "109", youtubeId: "JloiRQGhSqk", title: "[FULL SHOW] Featured Designer ORIGIN OF OCEANS | EXA MODELS | Miami Swim Week", category: "MSW" },
  { id: "110", youtubeId: "EMZ-Vs1s_M4", title: "EXA Models Miami Swim Week Designer Origin Of Oceans", category: "MSW" },
  { id: "111", youtubeId: "TmlwpfrT3hE", title: "Exa Models Belle | Miami Swim Week 2025 [4K]", category: "MSW" },
  { id: "112", youtubeId: "UlBtNsQfmdU", title: "EXA Models | Designer Goalden Swimwear | Miami Swim Week", category: "MSW" },
  { id: "113", youtubeId: "cmzxuA513Y0", title: "Featured Group | EXA MODELS | Designer ORIGIN OF OCEANS | Miami Swim Week 7", category: "MSW" },
  { id: "114", youtubeId: "XH3R0oUZsDU", title: "Featured Group | EXA MODELS | Designer OCEAN OF ORIGINS | Miami Swim Week 4", category: "MSW" },
  { id: "115", youtubeId: "yGw-i2n128o", title: "Miami Swim Week 2024 | Exa Models Coconut Bikini", category: "MSW" },
  { id: "116", youtubeId: "gEJqqFpTwH0", title: "Featured Group | EXA MODELS | Designer ORIGIN OF OCEANS | Miami Swim Week 6", category: "MSW" },
  { id: "117", youtubeId: "TXNCgD16XtY", title: "VEVE SWIM BIKINI EXTRAVAGANZA | Exa Models Miami Swim Week 2025 | 4K", category: "MSW" },

  // Miami Art Week / Art Basel - additional uploads
  { id: "118", youtubeId: "dEkeg8KPf8s", title: "Swim Shows EXA Models Designer Marky Swim | Miami Art Basel", category: "MAW", featured: true },
  { id: "119", youtubeId: "shAJ_e54gIQ", title: "Model Maya Manesis interviewed at Exa Shows Art Basel Miami in Brazilian Veve Swim", category: "MAW", featured: true },
  { id: "120", youtubeId: "PL92pob9fTI", title: "Swim Shows EXA Models | Bikini Flavors Swimsuit Swimwear | Miami Art Basel Week", category: "MAW" },
  { id: "121", youtubeId: "2jc2XSUTHZI", title: "Swim Shows EXA Models | Designer Color Super Swimwear | Miami Art Basel Week", category: "MAW" },
  { id: "122", youtubeId: "3xdR42UJJck", title: "Designer Pia Bolte at Art Basel Miami Exa Shows - Look 5", category: "MAW" },
  { id: "123", youtubeId: "LMZGiqobVRw", title: "Berry Beachy Closes the Show | EXA Models Art Basel 2025 Runway Finale", category: "MAW" },
  { id: "124", youtubeId: "xCfIwK943tA", title: "Model poses for photographer on the red carpet at Exa Shows Art Basel Miami", category: "MAW" },
  { id: "125", youtubeId: "Qc3MWRP5iAw", title: "Cuban Exa Model Eva Quiala interviewed on the red carpet at Exa Shows Art Basel Miami", category: "MAW" },
  { id: "126", youtubeId: "Z5hrRF1cB6c", title: "Full Show Monaco Swim Exa Models Bikini Runway Show Art Basel", category: "MAW" },
  { id: "127", youtubeId: "n9XBgmRk5KU", title: "Designer Josie Bikini at Art Basel Miami Exa Shows - Look 2", category: "MAW" },
  { id: "128", youtubeId: "1wPVb2gCzpM", title: "Inside EXA Models at Art Basel — Complete Runway Recap", category: "MAW" },
  { id: "129", youtubeId: "OJ-Rc0ZP2c4", title: "EXA Models Swim Shows | Designer LB Fashion Brand | Miami Art Basel Week", category: "MAW" },
  { id: "130", youtubeId: "lWDORRwYsMs", title: "SLOMO 4K Swim Shows | EXA Models | Josie Bikinis | Miami Art Basel", category: "MAW" },
  { id: "131", youtubeId: "6hia_GGMrzw", title: "Swim Shows EXA Models | Designer Oceanus Bikini | Miami Art Basel Week Runway", category: "MAW" },
  { id: "132", youtubeId: "Hy61H52wtjM", title: "4K EXA Models Runway Pre-Show & BTS | Miami Art Basel 2025 | EXA Swim", category: "MAW" },
  { id: "133", youtubeId: "-d1Pge64O98", title: "Bay Fashion Show | EXA Models Art Basel Showcase 2025", category: "MAW" },
  { id: "134", youtubeId: "B-r1Om7me0k", title: "Watch This ft. Studio Samariela Marky Swim | Swim Shows EXA Models Miami Art Basel", category: "MAW" },
  { id: "135", youtubeId: "zn_N3NFlc18", title: "Exa Models Full Day 2 Show | Miami Art Basel 2025", category: "MAW" },
  { id: "136", youtubeId: "T3Rd3SHkyzU", title: "Exa Models Miami Art Basel 2025 | Day 1 Full Show", category: "MAW" },
  { id: "137", youtubeId: "Knc3j8AQ0ao", title: "Exa Swim Exa Models | Day 1 Looks | Miami Art Basel 2025 [8K]", category: "MAW" },
  { id: "138", youtubeId: "VpHrunEe5Rg", title: "Josie Bikinis on the Art Basel Runway | EXA Models Showcase", category: "MAW" },
  { id: "139", youtubeId: "EEExmkreU2E", title: "4K Bikini SLOW MOTION | Capristan Swimwear Runway | EXA Models Art Basel Miami 2025", category: "MAW" },
  { id: "140", youtubeId: "R2YMy-xx260", title: "Bikini Flavors Art Basel Miami EXA Models EXA Shows", category: "MAW" },
  { id: "141", youtubeId: "ViVWlkOocRI", title: "Introducing IVY | Art Basel EXA Models Runway", category: "MAW" },
  { id: "142", youtubeId: "ye5YymK-fu4", title: "Veve Fashion Show | EXA Models Art Basel Showcase 2025", category: "MAW" },
  { id: "143", youtubeId: "IsIAZKxKpBs", title: "Exa Models pose for photographers on the red carpet at Exa Shows Art Basel Miami", category: "MAW" },
  { id: "144", youtubeId: "N-MWmAdG_zo", title: "Model Amber Fields on the red carpet at Exa Shows Art Basel Miami wearing Berry Beachy", category: "MAW" },
  { id: "145", youtubeId: "SLYV0-jVH6s", title: "Meduza Swimwear Brings the Heat at Art Basel | EXA Models Runway", category: "MAW" },
  { id: "146", youtubeId: "IDqku2JhI_Y", title: "Capristan | Exa Models | Miami Art Basel 2025 [8K]", category: "MAW" },
  { id: "147", youtubeId: "R-c7TZChpNQ", title: "Model Ashley interviewed at Exa Shows Art Basel Miami wearing Capristan", category: "MAW" },
  { id: "148", youtubeId: "YIbOWACAtCs", title: "Karen Rodriguez walking and posing on runway before Exa Models Art Basel Event", category: "MAW" },
  { id: "149", youtubeId: "zHS3A47pxLI", title: "Models Athena and Lola interviewed at EXA Shows at Miami Art Week", category: "MAW" },
  { id: "150", youtubeId: "Ivi7CT8uwJQ", title: "Interview with Claudia at Exa Shows Art Basel Miami wearing Capristan", category: "MAW" },
  { id: "151", youtubeId: "xK5XGZZO9LM", title: "Models Joanna and Alexandra interviewed at Exa Shows Art Basel Miami on the red carpet", category: "MAW" },
  { id: "152", youtubeId: "qIbKDjysRX0", title: "Model Ashley Lam interviewed at Exa Shows Art Basel Miami on the red carpet", category: "MAW" },
  { id: "153", youtubeId: "qBc9UCCMP8U", title: "Color Super - Exa Models - Miami Art Basel 2024 Fashion Show", category: "MAW" },
  { id: "154", youtubeId: "nD-mwbKIXzY", title: "Model Ashley Lam poses at Exa Shows Art Basel Miami on the red carpet", category: "MAW" },
  { id: "155", youtubeId: "cC0tu6hZF_8", title: "Model Luana Larkin poses at Exa Shows Art Basel Miami on the red carpet", category: "MAW" },
  { id: "156", youtubeId: "lJEAjrJ-0hY", title: "Designer Slay Swimwear at Art Basel Miami Exa Shows - Look 1", category: "MAW" },
  { id: "157", youtubeId: "fp_sENmlXig", title: "Models Maya Manesis and Esther Finnie interviewed at Exa Shows Art Basel Miami", category: "MAW" },
  { id: "158", youtubeId: "MeJXijZ448I", title: "Pia Bolte at Exa Shows Art Basel 2025", category: "MAW" },
  { id: "159", youtubeId: "77Sz43mMSgY", title: "Designer Meduza at Art Basel Miami Exa Shows - Look 25", category: "MAW" },
  { id: "160", youtubeId: "D8Q6qFSVmRA", title: "Model Luana Larkin interviewed at Exa Shows Art Basel Miami on the red carpet", category: "MAW" },

  // NYFW - additional uploads
  { id: "161", youtubeId: "r9YIK9ayXgw", title: "Dippin Daisys at New York Swim Collective Beautiful Bikinis Exa Models Fashion Show", category: "NYFW" },
  { id: "162", youtubeId: "43ih2yuKw_0", title: "Models Sydney Lint and Anny at Exa Shows NYFW", category: "NYFW" },
  { id: "163", youtubeId: "tl8li-nHGXI", title: "EXA Models Hit the Runway at New York Fashion Week | NYFW 2025", category: "NYFW" },

  // Behind the Scenes - additional uploads
  { id: "164", youtubeId: "utSI43E4lhA", title: "MINI VLOG: Content Day with Exa Models, BTS, Bikinis, Models Dominican Republic", category: "Behind the Scenes" },
  { id: "165", youtubeId: "Vtd1ZOthBBQ", title: "EXA Shows Casting", category: "Behind the Scenes" },
  { id: "166", youtubeId: "4FaCo65uh_c", title: "Exa Shows BTS Art Basel 2025", category: "Behind the Scenes" },
  { id: "167", youtubeId: "Tu9DemS0rO0", title: "Part 2 Content Day Mini Vlog with Exa Models, Cabrera DR", category: "Behind the Scenes" },
  { id: "168", youtubeId: "_T0Caf4I32c", title: "EXA Model Jaya Williams interviews model Virginia Sanhouse on Walking in Runway Shows for Swim Week", category: "Behind the Scenes" },
  { id: "169", youtubeId: "hKY3ce-7yIM", title: "Exa Models Swim Shows | Casting Art Basel 2025 | iPhone 17 Pro Max", category: "Behind the Scenes" },

  // Miami Swim Week 2026 — latest uploads (added 2026-06-13)
  { id: "170", youtubeId: "ZvK7lfb7OPY", title: "Serpent Swim | Full Runway Show | EXA Shows Miami Swim Week 2026", category: "MSW", featured: true },
  { id: "171", youtubeId: "r1FaOEmJrzw", title: "Berry Beachy Swimwear | Miami Swim Week 2026 | Exa Shows | Full Runway Show 4K", category: "MSW", featured: true },
  { id: "172", youtubeId: "kUg8qff2ak8", title: "Piura Swim & Akaló | Full Runway Show | EXA Shows Miami Swim Week 2026", category: "MSW" },
  { id: "173", youtubeId: "9aPlccxNmf8", title: "Quiala Collection Full Show | Miami Swim Week 2026 | Exa Shows", category: "MSW" },
  { id: "174", youtubeId: "dHYu9BBujeE", title: "Miami Swim Week 2026 Model Fashion Show 4K Slow Motion | EXA | Piura Swim", category: "MSW" },
  { id: "175", youtubeId: "UwyRA9OCwgU", title: "Capristan | Miami Swim Week 2026 | Official Full Show 4K | Exa Shows", category: "MSW" },
  { id: "176", youtubeId: "dS9HjnFX_Yg", title: "Berry Beachy | Full Runway Show 2026 | EXA Swim Shows Miami", category: "MSW" },
  { id: "177", youtubeId: "m6gz3Y2_-lc", title: "Exa Shows Miami Swim Week 2026 | Berry Beachy Showcase", category: "MSW" },
  { id: "178", youtubeId: "3a5cJhX9dH0", title: "Exa Shows | Miami Swim Week 2026 | Shows Coming Soon", category: "MSW" },
  { id: "179", youtubeId: "jKe57upWUqo", title: "Berry Beachy Bikini Watch Party | Miami Swim Week 2026 | Exa Shows", category: "Behind the Scenes" },
];

export const TV_CATEGORIES = [
  "All",
  "MSW",
  "MAW",
  "NYFW",
  "Behind the Scenes",
] as const;

export const CATEGORY_LABELS: Record<string, string> = {
  All: "All Shows",
  MSW: "Miami Swim Week",
  MAW: "Miami Art Week",
  NYFW: "New York Fashion Week",
  "Behind the Scenes": "Behind the Scenes",
};
