import { createClient } from "@supabase/supabase-js";
import * as dotenv from "dotenv";

dotenv.config({ path: ".env.local" });

const supabase = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL!,
  process.env.SUPABASE_SERVICE_ROLE_KEY!
);

// Curated list: tourism boards most likely to partner with lifestyle/fashion creators
// Prioritized by: active influencer programs, budget, destination appeal for creators, accessibility
const tourismContacts = [
  // === CARIBBEAN & ISLANDS (High Priority - luxury, aspirational, influencer-friendly) ===
  {
    brand_name: "Cayman Islands Department of Tourism",
    contact_name: null,
    email: "pr@caymanislands.ky",
    email_type: "pr",
    phone: "+1-345-949-0623",
    website_url: "https://www.visitcaymanislands.com",
    category: "tourism_board",
    contact_type: "tourism",
    location_city: "George Town",
    location_country: "KY",
    notes: "Partnered with Steller for influencer itineraries. 'Welcome to vaCay' campaign launched Oct 2025. Hosts FAM trips for influencers.",
  },
  {
    brand_name: "Saint Lucia Tourism Authority",
    contact_name: "Jennifer Maguire",
    email: "jennifer@jmc-pr.com",
    email_type: "pr",
    phone: "+1-212-579-0159",
    website_url: "https://www.stlucia.org",
    category: "tourism_board",
    contact_type: "tourism",
    location_city: "Castries",
    location_country: "LC",
    notes: "JMC-PR handles US PR. UK: Liz Fay lfay@stluciauk.org. Canada: andrew@totalpublicrelations.ca. General: information@stlucia.org. Actively welcomes bloggers and influencers.",
  },
  {
    brand_name: "Antigua and Barbuda Tourism Authority",
    contact_name: "Tameka Wharton",
    email: "twharton@visitaandb.com",
    email_type: "pr",
    phone: "+1-268-562-7600",
    website_url: "https://www.visitantiguabarbuda.com",
    category: "tourism_board",
    contact_type: "tourism",
    location_city: "St. John's",
    location_country: "AG",
    notes: "Also: matara.richards@visitaandb.com. General: info@visitaandb.com. UK: tourisminfouk@visitaandb.com. US NY office: +1-212-541-4117.",
  },
  {
    brand_name: "Curacao Tourist Board",
    contact_name: null,
    email: "info@curacao.com",
    email_type: "general",
    phone: "+599-9-434-8200",
    website_url: "https://www.curacao.com",
    category: "tourism_board",
    contact_type: "tourism",
    location_city: "Willemstad",
    location_country: "CW",
    notes: "Destination Services handles press and influencer trips. PR agency: Bright8 (Netherlands). Has run campaigns with 11+ influencers covering airfare, accommodations, meals, activities.",
  },
  {
    brand_name: "Dominican Republic Ministry of Tourism",
    contact_name: "Callie Murphy",
    email: "callie.murphy@bvk.com",
    email_type: "pr",
    phone: "+1-414-247-3897",
    website_url: "https://www.godominicanrepublic.com",
    category: "tourism_board",
    contact_type: "tourism",
    location_city: "Santo Domingo",
    location_country: "DO",
    notes: "BVK is PR/advertising agency of record for US market. Hosts media reps and influencers in-country. Media inquiries: godominicanrepublic.com/media/media-inquiries/.",
  },
  {
    brand_name: "Bermuda Tourism Authority",
    contact_name: "Kiwan Anderson",
    email: "kanderson@gotobermuda.com",
    email_type: "pr",
    phone: "+1-441-296-9200",
    website_url: "https://www.gotobermuda.com",
    category: "tourism_board",
    contact_type: "tourism",
    location_city: "Hamilton",
    location_country: "BM",
    notes: "Director of Global Communications, PR & Content Development. PR agency: BerlinRosen. Has DEDICATED influencer request form at gotobermuda.com/bta/influencer-request-form.",
  },
  {
    brand_name: "Belize Tourism Board",
    contact_name: null,
    email: "media@travelbelize.org",
    email_type: "press",
    phone: "+1-800-624-0686",
    website_url: "https://www.travelbelize.org",
    category: "tourism_board",
    contact_type: "tourism",
    location_city: "Belize City",
    location_country: "BZ",
    notes: "Has dedicated request forms for influencer/content creator inquiries. PR agency: The Zimmerman Agency. Requires 4 weeks advance notice. Targets US, Canada, Mexico, Europe.",
  },
  {
    brand_name: "St. Kitts Tourism Authority",
    contact_name: "Jonette Boyd",
    email: "jonette.boyd@stkittstourism.kn",
    email_type: "pr",
    phone: "+1-869-465-4040",
    website_url: "https://www.visitstkitts.com",
    category: "tourism_board",
    contact_type: "tourism",
    location_city: "Basseterre",
    location_country: "KN",
    notes: "Communications & Marketing Manager. In Virtuoso luxury travel portfolio. Seeking PR agency for traveler attraction as of Oct 2025.",
  },

  // === CENTRAL & SOUTH AMERICA (trending creator destinations) ===
  {
    brand_name: "Costa Rica Tourism Board (ICT)",
    contact_name: null,
    email: "prensa@ict.go.cr",
    email_type: "press",
    phone: "+506-2299-5800",
    website_url: "https://www.visitcostarica.com",
    category: "tourism_board",
    contact_type: "tourism",
    location_city: "San Jose",
    location_country: "CR",
    notes: "Selects niche influencers for US/Canadian markets. 'Essential Costa Rica' brand. Works with MMGY agency. Press trips page: ict.go.cr/en/institutional-services/press-trips.html.",
  },
  {
    brand_name: "ProColombia",
    contact_name: null,
    email: "prensa@procolombia.co",
    email_type: "press",
    phone: "+57-1-560-0100",
    website_url: "https://colombia.travel",
    category: "tourism_board",
    contact_type: "tourism",
    location_city: "Bogota",
    location_country: "CO",
    notes: "Promotes tourism, FDI, exports. Organizes press trips with international journalists and influencers. Press Room: procolombia.co/en/press-room. Targets US, Spain, UK.",
  },
  {
    brand_name: "Embratur - Brazilian Tourist Board",
    contact_name: null,
    email: "marketing@embratur.gov.br",
    email_type: "pr",
    phone: "+55-61-2023-7900",
    website_url: "https://www.visitbrasil.com",
    category: "tourism_board",
    contact_type: "tourism",
    location_city: "Brasilia",
    location_country: "BR",
    notes: "Partnership with TikTok for influencer campaigns. Promotes press trips to Carnival. Offices in US, UK, France, Germany, Italy, Japan, Portugal, Spain.",
  },

  // === EUROPE (aspirational, high-end creator destinations) ===
  {
    brand_name: "Turespana - Visit Spain",
    contact_name: null,
    email: "nuevayork@tourspain.es",
    email_type: "general",
    phone: "+1-212-265-8822",
    website_url: "https://www.spain.info",
    category: "tourism_board",
    contact_type: "tourism",
    location_city: "Madrid",
    location_country: "ES",
    notes: "33 Tourist Offices worldwide. NY office: 60 E 42nd St #5300. Influencer marketing is key pillar — works with micro and macro influencers. Newsroom: socialnewsroom.spain.info.",
  },
  {
    brand_name: "ENIT - Italian National Tourist Board",
    contact_name: "Flavio Zappacosta",
    email: "flavio.zappacosta@enit.it",
    email_type: "press",
    phone: "+44-207-399-3551",
    website_url: "https://www.italia.it",
    category: "tourism_board",
    contact_type: "tourism",
    location_city: "Rome",
    location_country: "IT",
    notes: "Government-funded. Won Clic d'Or awards for influencer campaigns. Works with tour operators, travel agencies, journalists, influencers globally. Consumer site: italia.it.",
  },
  {
    brand_name: "Atout France",
    contact_name: null,
    email: "press.us@atout-france.fr",
    email_type: "press",
    phone: "+1-212-745-0967",
    website_url: "https://www.france.fr",
    category: "tourism_board",
    contact_type: "tourism",
    location_city: "Paris",
    location_country: "FR",
    notes: "France Tourism Development Agency. UK press: pressoffice.uk@atout-france.fr. 1,100+ members. Specializes in influencer marketing, media relations, partnerships. US media: us.media.france.fr/en/contact.",
  },
  {
    brand_name: "Croatian National Tourist Board",
    contact_name: null,
    email: "info.us@croatia.hr",
    email_type: "general",
    phone: "+1-212-279-8672",
    website_url: "https://www.croatia.hr",
    category: "tourism_board",
    contact_type: "tourism",
    location_city: "Zagreb",
    location_country: "HR",
    notes: "US office: 33 Irving Pl, New York. UK: info@croatia-london.co.uk +44-203-668-3800. HQ: info@htz.hr +385-1-4556-455. Exploded in popularity via social media (Game of Thrones effect).",
  },
  {
    brand_name: "Business Iceland / Visit Iceland",
    contact_name: null,
    email: "press@businessiceland.is",
    email_type: "press",
    phone: "+354-511-4000",
    website_url: "https://www.inspiredbyiceland.com",
    category: "tourism_board",
    contact_type: "tourism",
    location_city: "Reykjavik",
    location_country: "IS",
    notes: "Brand: Inspired by Iceland. Visit Reykjavik PR: PR@visitreykjavik.is. Regional managers for North America, France, Germany, UK. Organized press trips with PR offices.",
  },
  {
    brand_name: "Tourism Ireland",
    contact_name: null,
    email: "info@tourismireland.com",
    email_type: "general",
    phone: "+353-1-476-3400",
    website_url: "https://www.tourismireland.com",
    category: "tourism_board",
    contact_type: "tourism",
    location_city: "Dublin",
    location_country: "IE",
    notes: "Hosted 1,000+ journalist and influencer visits. Allocating 350K+ EUR toward social media influencer engagement. Media room: media.ireland.com. HQ: Bishop's Square, Redmond's Hill, Dublin 2.",
  },
  {
    brand_name: "VisitScotland",
    contact_name: null,
    email: "pressoffice@visitscotland.com",
    email_type: "press",
    phone: "+44-131-472-2222",
    website_url: "https://www.visitscotland.com",
    category: "tourism_board",
    contact_type: "tourism",
    location_city: "Edinburgh",
    location_country: "GB",
    notes: "Has influencer application form: visitscotland.org/who-we-are/contact/influencer-programmes. Content creator network form available. Case-by-case collaborations.",
  },
  {
    brand_name: "Malta Tourism Authority",
    contact_name: "Kearon Bruno",
    email: "kearon.c.bruno@visitmalta.com",
    email_type: "partnerships",
    phone: "+356-2291-5000",
    website_url: "https://www.visitmalta.com",
    category: "tourism_board",
    contact_type: "tourism",
    location_city: "Valletta",
    location_country: "MT",
    notes: "Brand Partnerships & Innovation. Marketing: Arthur Grima arthur.grima@visitmalta.com. General: info@visitmalta.com. Overseas offices and PR agents in key markets.",
  },

  // === AFRICA & MIDDLE EAST (big budgets, actively recruiting creators) ===
  {
    brand_name: "Moroccan National Tourist Office (ONMT)",
    contact_name: "Hasna Kaissoumi",
    email: "contact@onmt.org.ma",
    email_type: "general",
    phone: "+212-537-27-80-00",
    website_url: "https://www.visitmorocco.com",
    category: "tourism_board",
    contact_type: "tourism",
    location_city: "Rabat",
    location_country: "MA",
    notes: "Strategic Marketing and Communication Director. 'Visit Morocco Originals' video series. Partners with tour operators, travel agents, airlines, journalists. International offices in key markets.",
  },
  {
    brand_name: "South African Tourism",
    contact_name: null,
    email: "mediaq@southafrica.net",
    email_type: "press",
    phone: "+27-11-895-3000",
    website_url: "https://www.southafrica.net",
    category: "tourism_board",
    contact_type: "tourism",
    location_city: "Johannesburg",
    location_country: "ZA",
    notes: "Official media inquiry email. Hosts annual Tourism Indaba in Durban (one of top 3 global tourism marketing events). Corporate: southafrica.net/gl/en/corporate/contact-us.",
  },
  {
    brand_name: "DCT Abu Dhabi",
    contact_name: null,
    email: "Media-DCTAbuDhabi@DCTAbuDhabi.ae",
    email_type: "press",
    phone: "+971-2-444-0444",
    website_url: "https://visitabudhabi.ae",
    category: "tourism_board",
    contact_type: "tourism",
    location_city: "Abu Dhabi",
    location_country: "AE",
    notes: "Destination Marketing: DestinationMarketing@DCTAbuDhabi.ae. Influencer agency partner: Ykone (since 2020, hundreds of influencers). General: info@dctabudhabi.ae.",
  },
  {
    brand_name: "Saudi Tourism Authority",
    contact_name: "Steve Bowen",
    email: "info@sta.gov.sa",
    email_type: "general",
    phone: "+966-11-880-8855",
    website_url: "https://www.visitsaudi.com",
    category: "tourism_board",
    contact_type: "tourism",
    location_city: "Riyadh",
    location_country: "SA",
    notes: "VP of Public Relations and Communication. 300+ content creators hosted on 26 trips (2022-2023). Media Center: sta.gov.sa/en/media-center. Massive budget — actively recruiting influencers.",
  },
  {
    brand_name: "Jordan Tourism Board",
    contact_name: "Janine",
    email: "janine@visitjordan.com",
    email_type: "pr",
    phone: "+962-6-567-8444",
    website_url: "https://www.myjordanjourney.com",
    category: "tourism_board",
    contact_type: "tourism",
    location_city: "Amman",
    location_country: "JO",
    notes: "JTBNA handles integrated comms, digital marketing, and media relations. North America office: 1420 Beverly Rd Suite 203, McLean VA 22101. Media form: myjordanjourney.com/media-form.",
  },
  {
    brand_name: "Egyptian Tourism Authority",
    contact_name: "Kamila Giraldo",
    email: "egypttourism@mcgroup.com",
    email_type: "pr",
    phone: "+20-2-2735-8861",
    website_url: "https://egypt.travel",
    category: "tourism_board",
    contact_type: "tourism",
    location_city: "Cairo",
    location_country: "EG",
    notes: "PR handled by Media consulta International (Kamila Giraldo, Account Manager). Hosts influencers and journalists. Partnership with Wego for promotion.",
  },

  // === ASIA & PACIFIC (strong influencer programs) ===
  {
    brand_name: "Tourism Australia",
    contact_name: null,
    email: "internationalmedia@tourism.australia.com",
    email_type: "press",
    phone: "+61-2-9360-1111",
    website_url: "https://www.australia.com",
    category: "tourism_board",
    contact_type: "tourism",
    location_city: "Sydney",
    location_country: "AU",
    notes: "Media Hosting Program hosts 400-600 media/influencers annually from 16+ countries. Also: mediapitch@tourism.australia.com. One of the best influencer programs globally.",
  },
  {
    brand_name: "Tourism New Zealand",
    contact_name: null,
    email: "newsroom@tnz.govt.nz",
    email_type: "press",
    phone: "+64-4-462-8000",
    website_url: "https://www.newzealand.com",
    category: "tourism_board",
    contact_type: "tourism",
    location_city: "Wellington",
    location_country: "NZ",
    notes: "Award-winning digital marketing. Marketing partnerships: tourismnewzealand.com/partner-with-us/marketing-activity/. Media site: media.newzealand.com. Targets professionals aged 25-54.",
  },
  {
    brand_name: "Japan National Tourism Organization (JNTO)",
    contact_name: null,
    email: "press_uk@jnto.go.jp",
    email_type: "press",
    phone: "+81-3-6691-3893",
    website_url: "https://www.japan.travel",
    category: "tourism_board",
    contact_type: "tourism",
    location_city: "Tokyo",
    location_country: "JP",
    notes: "26 offices worldwide. Digital Marketing: digital@jnto.go.jp. Hosts JNTO Influencer Seminars. Fully revamped Online Media Center. Post-COVID tourism push actively seeking creators.",
  },
  {
    brand_name: "Tourism Fiji",
    contact_name: "Josefa Tuamoto",
    email: "jtuamoto@fiji.travel",
    email_type: "general",
    phone: "+679-672-2433",
    website_url: "https://www.fiji.travel",
    category: "tourism_board",
    contact_type: "tourism",
    location_city: "Nadi",
    location_country: "FJ",
    notes: "CEO. Australian PR/influencer agency: Havas Red. Corporate: corporate.fiji.travel. Brand: 'Where Happiness Comes Naturally'. Key markets: Australia, NZ, USA.",
  },
  {
    brand_name: "Singapore Tourism Board",
    contact_name: null,
    email: "STB_TA@STB.GOV.SG",
    email_type: "general",
    phone: "+65-6736-6622",
    website_url: "https://www.visitsingapore.com",
    category: "tourism_board",
    contact_type: "tourism",
    location_city: "Singapore",
    location_country: "SG",
    notes: "Massive marketing budget. Media Centre: stb.gov.sg/about-stb/media-publications/media-centre/. Email format: first_last@stb.gov.sg. TIH portal: tih.stb.gov.sg for industry partners.",
  },
  {
    brand_name: "Korea Tourism Organization",
    contact_name: null,
    email: "info@knto.or.kr",
    email_type: "general",
    phone: "+82-33-738-3000",
    website_url: "https://english.visitkorea.or.kr",
    category: "tourism_board",
    contact_type: "tourism",
    location_city: "Wonju",
    location_country: "KR",
    notes: "30 overseas offices. K-influencer program (Adventure Korea). Email format: First_Last@visitkorea.or.kr. Under Ministry of Culture, Sports and Tourism.",
  },
  {
    brand_name: "Philippines Department of Tourism",
    contact_name: "Czarina Zara-Loyola",
    email: "czloyola@tourism.gov.ph",
    email_type: "pr",
    phone: "+63-2-8459-5200",
    website_url: "https://www.tourism.gov.ph",
    category: "tourism_board",
    contact_type: "tourism",
    location_city: "Makati City",
    location_country: "PH",
    notes: "Assistant Secretary for Strategic Communications. Brand: Love the Philippines. Tourism Promotions Board: info@tpb.gov.ph. US offices: philippinetourismusa.com.",
  },
];

async function main() {
  console.log(`Inserting ${tourismContacts.length} tourism board contacts (batch 2)...\n`);

  let inserted = 0;
  let skipped = 0;

  for (const contact of tourismContacts) {
    // Check if already exists
    const { data: existing } = await supabase
      .from("brand_outreach_contacts")
      .select("id")
      .eq("email", contact.email)
      .single();

    if (existing) {
      console.log(`  Already exists: ${contact.brand_name} (${contact.email})`);
      skipped++;
      continue;
    }

    const { error } = await supabase
      .from("brand_outreach_contacts")
      .insert({
        ...contact,
        status: "new",
      });

    if (error) {
      console.log(`  Error inserting ${contact.brand_name}: ${error.message}`);
    } else {
      console.log(`  Inserted: ${contact.brand_name}`);
      inserted++;
    }
  }

  console.log(`\nDone! Inserted: ${inserted}, Skipped: ${skipped}`);
  console.log(`Total tourism contacts now: ${inserted + skipped + 20} (including batch 1)`);
}

main().catch(console.error);
